---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contrast-agent-access
rules:
- apiGroups: ["agents.contrastsecurity.com"]
  resources: ["AgentInjector", "AgentInjectorConfigs"]
  verbs: ["create", "list", "delete", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contrast-agent-access-binding
subjects:
- kind: User
  name: svsdevops
  namespace: ocp-ddp-rnd
roleRef:
  kind: ClusterRole
  name: contrast-agent-access
  apiGroup: rbac.authorization.k8s.io
